CREATE TABLE AIRLINE
( 
AIRLINE_NAME VARCHAR(50),
  FLIGHT_TIME TIME,
  BODY_TYPE VARCHAR(20),
  NO_OF_SEAT INT,
  DESTINATION VARCHAR(50),
  NO_OF_EMPLOYEE INT,
  FLIGHT_NO VARCHAR(15),
  PASSENGER_INFO VARCHAR(50),
  CLASS VARCHAR(15),
  GENDER VARCHAR(6),
  COUNTRY_OWNERSHIP VARCHAR(30),
  TRANSIT VARCHAR(30)
)

SELECT *FROM AIRLINE
--DROP TABLE AIRLINE

INSERT INTO AIRLINE VALUES ('AMERICAN AIRLINES', '10:00 AM', 'NARROW BODY', '50', 
'SAN FRANCISCO', '300', 'ABC123', 'BASANTA ADHIKARI', 'ECONOMY','MALE', 'USA', 'LAS VEGAS')
 
 INSERT INTO AIRLINE VALUES ('DELTA', '11:00 AM', 'WIDE BODY', '150', 
'SACRAMENTO', '600', 'DEF456', 'SIMON LAMA', 'PREMIUM ECONOMY','FEMALE', 'CANADA', 'COLORADO')

INSERT INTO AIRLINE VALUES ('YETI', '12:00 PM', 'COMMUTER', '20', 
'NEPALGUNJ', '45', 'GHI789', 'BINOD THAPA', 'BUSINESS','MALE', 'NEPAL', 'BUTWAL')

INSERT INTO AIRLINE VALUES ('QATAR AIRLINES', '01:00 PM', 'REGIONAL_AIRLINER', '75', 
'DOHA', '150', 'JKL012', 'ISHWOR THAPA', 'FIRST CLASS','MALE', 'QATAR', 'DELHI')

INSERT INTO AIRLINE VALUES ('TURKISH AIRLINES', '02:00 PM', 'BOEING', '350', 
'DUBAI', '550', 'MNP345', 'SURESH KHADKA', 'ECONOMY','MALE', 'TURKEY', 'KOREA')

SELECT *FROM AIRLINE


01/13/2023 OM SIR

CREATE TABLE SWEET_CREPES_MENU
( 
FLAVOUR VARCHAR(50),
PRICE VARCHAR(10),
IN_STOCK VARCHAR(15),
TEMPERATURE VARCHAR(15),
DENSITY VARCHAR(15),
AIR_CONTENT VARCHAR(15),
FAT_CONTENT VARCHAR(15),
PRICE VARCHAR(15),
)

CREATE TABLE SWEET_CREPES
( 
CREPE_ID INT,
CREPE_NAMES VARCHAR (50),
PRICE DECIMAL(10,2),
CREPE_DESCRIPTION VARCHAR (130),
)

SELECT *FROM SWEET_CREPES

--DROP TABLE SWEET_CREPES

INSERT INTO SWEET_CREPES VALUES(1, 'PLAIN', '6.50','NUTELLA,BANANA,STRAWBERRY,CORN FLAKES, FRESH CREAM')

INSERT INTO SWEET_CREPES VALUES(2, 'PLAIN W/GRANOLA', '7.50','BANANA,STRAWBERRY,SLICED ALMONDS ,FRESH CREAM, NUTELLA')

INSERT INTO SWEET_CREPES VALUES(3, 'PLAIN W/ALMONDA', '7.50','BANANA,STRAWBERRY,SLICED ALMONDS, FRESH CREAM,NUTELLA')

INSERT INTO SWEET_CREPES VALUES(4, 'PLAIN W/BISCOFF_COOKIE BUTTER', '7.50', 'BISCOFF COOKIE BUTTER, BANANA,STRAWBERRY,SLICED_ALMONDS, FRESH CREAM,NUTELLA')

INSERT INTO SWEET_CREPES VALUES(5, 'VERY BERRY MUCH', '8.00', 'STRAWBERRY,BLUEBERRY, RASPBERRY, GRAPE, FRESH CREAM, YOGURT CREAM,POWDERED SUGAR')

INSERT INTO SWEET_CREPES VALUES(6, 'MOCHI LAND', '7.50', 'RED BEAN PASTE, MOCHI, SLICED ALMONDS, FRESH CREAM, SWEET MILK')

INSERT INTO SWEET_CREPES VALUES(7, 'MOCHI LAND W/STRAWBERRY & GREEN TEA ICE CREAM', '8.00', 'RED BEAN PASTE, MOCHI, FRESH STRAWBERRIES, GREEN TEA ICE CREAM, FRESH CREAM, SLICED ALMONDS')

INSERT INTO SWEET_CREPES VALUES(8, 'COOKIE & CREME', '7.00', 'OREO COOKIES, FRESH CREAM, CHOCOLATE SYRUP, CHOCOLATE SPRINKLES')

INSERT INTO SWEET_CREPES VALUES(9, 'MALLOW STORM', '7.00', 'MARSHMALLOW, GRAHAM CRACKERS, CHOCOLATE CREAM, CHOCOLATE SYRUP')

INSERT INTO SWEET_CREPES VALUES(10, 'STRAWBERRY STRAWBERRY ', '8.00', 'FRESH STRAWBERRIES, STRAWBERRY ICE CREAM, NUTELLA, CUSTARD CREAM, FRESH CREAM, BERRY SAUCE')

INSERT INTO SWEET_CREPES VALUES(11, 'STRAWBERRY STRAWBERRY W/ BANANA', '8.25', 'FRESH STRAWBERRIES, BANANA, STRAWBERRY ICE CREAM, NUTELLA, CUSTARD CREAM, FRESH CREAM, CHOCO SAUCE ')

INSERT INTO SWEET_CREPES VALUES(12, 'MANGO MANGO', '8.50', 'FRESH MANGO, MANGO ICE CREAM, NUTELLA, CUSTARD CREAM, FRESH CREAM, BERRY SAUCE')

INSERT INTO SWEET_CREPES VALUES(13, 'MANGO MANGO W/ RASPBERRY', '8.75', 'FRESH MANGO, RASPBERRY, MANGO ICE CREAM, NUTELLA, CUSTARD CREAM, FRESH CREAM, BERRY SAUCE')

INSERT INTO SWEET_CREPES VALUES(14, 'STRAWBERRY SUNDAE', '8.00', 'FRESH STRAWBERRY, VANILLA ICE CREAM, OREO COOKIE CRUMBS, SLICED ALMONDS, NUTELLA, FRESH CREAM, STRAWBERRY SAUCE')

INSERT INTO SWEET_CREPES VALUES(15, 'BANANA SPLIT', '8.00', 'BANANA, VANILLA ICE CREAM, OREO COOKIE CRUMBS, SLICED ALMONDS, NUTELLA, FRESH CREAM, CHOCOLATE SAUCE')

INSERT INTO SWEET_CREPES VALUES(16, 'MACARON CREPE', '9.00', 'MACARONS, VANILLA ICE CREAM, RASPBERRY, BLUEBERRY, FRESH CREAM, SEA SALT CARAMEL SAUCE')

INSERT INTO SWEET_CREPES VALUES(17, 'TIRAMISU', '7.50', 'TIRAMISU, FRESH CREAM, COCOA POWDER, CHOCOLATE SYRUP, PIROULINE, LOTUS BOSCOFF CRUMBS')

INSERT INTO SWEET_CREPES VALUES(18, 'CHEESECAKE BLISS STRAWBERRY', '8.25', 'FRESH STRAWBERRY, CHEESECAKE, VANILLA ICE CREAM, FRESH CREAM, SAUCE')

INSERT INTO SWEET_CREPES VALUES(19, 'CHEESECAKE BLISS OREO COOKIES', '8.00', 'OREO COOKIE CRUMBS, CHEESECAKE, VANILLA ICE CREAM, FRESH CREAM, SAUCE')

SELECT *FROM SWEET_CREPES













-- SYSTEM DEFINE FUNCTION

SELECT *FROM FRIEND_RELATIVE_INFO

SELECT NAME, LOWER(NAME) FROM FRIEND_RELATIVE_INFO

SELECT NAME, UPPER(NAME) FROM FRIEND_RELATIVE_INFO

SELECT NAME, LEN(NAME) FROM FRIEND_RELATIVE_INFO

SELECT NAME, LEFT(NAME,2) , RIGHT(NAME,3) FROM FRIEND_RELATIVE_INFO

SELECT NAME, SUBSTRING(NAME,2,5) FROM FRIEND_RELATIVE_INFO

SELECT NAME, SUBSTRING(NAME,1,2), LEFT(NAME,2) FROM FRIEND_RELATIVE_INFO